### ISSUE TITLE
Spark v3 support

### ISSUE THREAD

**Issue by ordukhanian** [itsumma/spark-greenplum-connector#10]
Hello,
The documention mentions that spark3 branch should be used for Spark v3.   
Could not find spark3 branch, and also there is no spark-greenplum-connector release for Spark v3.

Does spark-greenplum-connector support Spark v3?
Please let me know how to find the sources to build or released artifact for Spark v3.

**Comment by ordukhanian** [comment]
@hovercraft-github , could you please assist?

**Comment by hovercraft-github** [comment]
Spark v3 has quite a different internal API - that's why connector for it need a separate release.
Yes, we have released connector for Spark v2 only so far.
We have no a strict schedule, but hope v3 connector will be available in the next month.

**Comment by ordukhanian** [comment]
Hello @hovercraft-github ,
Are there any updates on Spark v3 support?

**Comment by hovercraft-github** [comment]
Just released v3.1.0 for spark3
