### ISSUE TITLE
Publishing package to Maven Central 

### ISSUE THREAD

**Issue by dolfinus** [itsumma/spark-greenplum-connector#8]
Building package every time it is not very convenient. What do you think about publishing package to Maven Central?

**Comment by hovercraft-github** [comment]
Of course you are right! We consider to do it maybe in the next release.

**Comment by dolfinus** [comment]
When is the next release date?

**Comment by hovercraft-github** [comment]
We have no a strict schedule, but hope this will happen near the end of this year.

**Comment by dolfinus** [comment]
Well...

**Comment by hovercraft-github** [comment]
Sorry, due to some non-technical reasons we will not publish this project into maven for a while,
but there is still possibility that we re-consider it later.
